const { Client } = require('pg');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.resolve(process.cwd(), '.env.local') });

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_KEY in environment.');
  process.exit(1);
}

const { hostname } = new URL(SUPABASE_URL);
const connectionString = `postgresql://postgres:${encodeURIComponent(
  SUPABASE_SERVICE_KEY
)}@${hostname}:5432/postgres`;

(async () => {
  const client = new Client({
    connectionString,
    ssl: { rejectUnauthorized: false },
  });

  try {
    await client.connect();

    const createTableSql = `
      CREATE TABLE IF NOT EXISTS orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        companyName TEXT NOT NULL,
        quantity INTEGER NOT NULL,
        sizeValue DOUBLE PRECISION NOT NULL,
        sizeLabel TEXT NOT NULL,
        canName TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'غير متاح',
        createdAt TIMESTAMPTZ NOT NULL
      );
    `;

    await client.query(createTableSql);
    console.log('Supabase table orders created or already exists.');
  } catch (error) {
    console.error('Error creating Supabase table:', error.message || error);
    process.exit(1);
  } finally {
    await client.end();
  }
})();
