const { Client } = require('pg');
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.resolve(process.cwd(), '.env.local') });

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;
const SUPABASE_DB_CONNECTION = process.env.SUPABASE_DB_CONNECTION;

let connectionString = null;

if (SUPABASE_DB_CONNECTION) {
  // Use direct provided Postgres connection string (preferred if Service Role key not available)
  connectionString = SUPABASE_DB_CONNECTION;
} else if (SUPABASE_URL && SUPABASE_SERVICE_KEY) {
  const { hostname } = new URL(SUPABASE_URL);
  connectionString = `postgresql://postgres:${encodeURIComponent(SUPABASE_SERVICE_KEY)}@${hostname}:5432/postgres`;
} else {
  console.error('Missing SUPABASE_DB_CONNECTION or SUPABASE_SERVICE_KEY in environment.');
  process.exit(1);
}

(async () => {
  const client = new Client({
    connectionString,
    ssl: { rejectUnauthorized: false },
  });

  try {
    await client.connect();

    const createTableSql = `
      CREATE TABLE IF NOT EXISTS orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        companyName TEXT NOT NULL,
        quantity INTEGER NOT NULL,
        sizeValue DOUBLE PRECISION NOT NULL,
        sizeLabel TEXT NOT NULL,
        canName TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'غير متاح',
        createdAt TIMESTAMPTZ NOT NULL
      );
    `;

    await client.query(createTableSql);
    console.log('Supabase table orders created or already exists.');
  } catch (error) {
    console.error('Error creating Supabase table:', error.message || error);
    process.exit(1);
  } finally {
    await client.end();
  }
})();
